### ISSUE TITLE
Progress animation stopped working when app moves background and then foreground

### ISSUE THREAD

**Issue by satishazad** [kamirana4/MKProgress#1]
When MKProgress view is visible. Move app in background and then move app in foreground, Progress animation stopped working.

**Comment by kamirana4** [comment]
@satishazad Thanks for reporting the issue. I will verify and push the fix.

**Comment by kamirana4** [comment]
Please update pod version to 1.0.9 for the fix.

**Comment by satishazad** [comment]
@kamirana4 Thanks
